accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),    
]

blog_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),  
    path('accounts/',include('django.contrib.auth.urls')),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('<int:pk>/', views.PostDetail.as_view(), name='detail'),
    path('delete/<int:pk>/', views.PostDelete.as_view(), name='delete'),
    path('drafts/', views.DraftList.as_view(), name='post_draft_list'),
    path('<int:pk>/publish/', views.post_publish, name='post_publish'),
    path('<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/delete/', views.delete_comment, name='comment_delete'),
]

accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser
from django.db.models.fields import CharField
from django.db import models
from django.contrib.auth.models import PermissionsMixin

class Profile(AbstractUser):
    username = CharField(max_length=30, unique=True)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'username'

    def __str__(self):
        return self.username

posts/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth import get_user_model

User = get_user_model()



class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    draft = models.BooleanField(default=False)

    def publish(self):
        self.create_date = timezone.now()
        self.draft = False
        self.save()

    def save_draft(self):
        self.draft = True
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('post_list')

    def __str__(self):
        return self.post.title
        return self.user.username

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from accounts.models import Profile

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = Profile

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['username'].label = 'Username'
            self.fields['email'].label = 'Email Address'

posts/forms.py
from django import forms
from django.forms import widgets
from posts.models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text', 'draft',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from . import forms
from django.views.generic import CreateView, DetailView
from django.http.response import HttpResponse
from accounts.models import Profile
from django.contrib.auth import views as auth_views

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

blog_app/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'index.html'

posts/views.py
from django.http import request
from .models import Post
from django.contrib.auth import login
from django.db import models
from django.shortcuts import redirect, render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic.detail import DetailView
from posts.models import Post, Comment
from django.views.generic import CreateView, DeleteView, ListView
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from posts.forms import PostForm, CommentForm


class PostList(ListView):
    model = Post
    http_method_name = ['GET']
    template_name = 'posts/post_list.html'


    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)


    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args, **kwargs) 
        post_list = Post.objects.all()
        context['post_list'] = post_list
        return context

class PostDetail(DetailView):
    model = Post


class CreatePost(CreateView, LoginRequiredMixin):
    login_url = '/login/'
    redirect_field_name = reverse_lazy('detail')
    model = Post
    form_class = PostForm
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class DraftList(ListView, LoginRequiredMixin):
    model = Post
    template_name = 'posts/post_draft_list.html'

    def get_queryset(self):
        return Post.objects.filter(draft=True).order_by('-create_date')

class PostDelete(DeleteView, LoginRequiredMixin):
    model = Post
    success_url = reverse_lazy('posts:all')


@login_required
def post_draft(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.draft()
    return redirect("posts:detail", pk=pk)

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.create_date = timezone.now()
    post.publish()
    return redirect("posts:detail", pk=pk)

@login_required
def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect("posts:detail", pk=post_pk)

@login_required
def add_comment_to_post(request,pk):
    post = get_object_or_404(Post,pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user 
            comment.save()
            return redirect('posts:detail',pk=post.pk)
    else:
        form = CommentForm()
    return render(request,'posts/comment_form.html',{'form':form})

accounts/templates/accounts/login.html
{% extends 'base.html' %} 
{% load bootstrap5 %} 
{% block body %}
<div class="containter">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %} 
        {% bootstrap_form form %}
        <button class="btn btn-success">Login</button>
    </form>
</div>
{% endblock body %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %} 
{% block body %}
<div class="containter">
    <h1>Sign Up!</h1>
    <form method="POST">
        {% csrf_token %} 
        {% bootstrap_form form %}
        <button class="btn btn-success">Sign up</button>
    </form>
</div>
{% endblock body %}

posts/templates/posts/comment_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}
{% block body %}
    <h1>
        Add a comment to the post...
    </h1>
    <form method="POST" class="post-form">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Post comment</button>
    </form>
{% endblock body %}

posts/templates/posts/post_confirm_delete.html
{% extends 'base.html' %}
{% block body %}
    <form method="POST">
    {% csrf_token %}
    <h1>Are you sure you want to delete the post?</h1>
    <br/>
    <button class="btn btn-danger px-5" type="submit">Delete</button>
    </form>
{% endblock body %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block body %}
    <h1>{{ post.title }}</h1>
        <h5> Author: {{ post.author.username }} </h5>
        <h5> {{ post.create_date }} </h5>
    <p>{{ post.text|linebreaksbr }}</p>
    {% if post.draft %}
    <p class="text-danger">Draft</p>
    <a class="btn btn-warning px-5" href="{% url 'posts:post_publish' pk=post.pk %}">Publish post</a>
    {% endif %}
    {% if user.is_authenticated %}
        {% if user.id == post.author.id %}
        <a class="btn btn-danger px-5" href="{% url 'posts:delete' pk=post.pk %}">Delete Post</a>
        <hr>
    {% endif %}
    {% endif %}
    {% if post.draft %}
    {% else %}
    <h3>Comments:</h3><hr/>
        {% for comment in post.comments.all %}
        <h3>{{ comment.text|linebreaksbr }}</h3>
        <p>{{ comment.author }} - {{ comment.create_date }}</p>   
        {% if user.is_authenticated %}
            {% if user.id == comment.author.id %}
            <a class="btn btn-danger px-5" href="{% url 'posts:comment_delete' pk=comment.pk %}">Delete Comment</a>
            {% endif %}
        {% endif %} 
        <hr>    
        {% empty %}
            <p>No comments yet...</p>
    {% endfor %}
    <a class="btn btn-success px-5 mb-5" href="{% url 'posts:add_comment_to_post' pk=post.pk %}">Add Comment</a>
    {% endif %}
{% endblock body %}

posts/templates/posts/post_draft_list.html
{% extends 'base.html' %}
{% block body %}
    {% for post in post_list %}
    {% if post.draft %}
        {% if user.id == post.author.id %}
            <h1><a href="{% url 'posts:detail' pk=post.pk %}" style="text-decoration:none;">{{ post.title }}</a></h1>
                <p>Author: {{ post.author }}</p>
                <hr>
            {% endif %}
        {% endif %}
        {% empty %}
        <h1>No drafts available...</h1>
    {% endfor %}
{% endblock body %}

posts/templates/posts/post_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}
{% block body %}
    <h1>Create a new post!</h1>
    <form method="POST" class="post-form">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success px-5">Create Post</button>
    </form>
{% endblock body %}

posts/templates/posts/post_list.html
{% extends 'base.html' %}
{% block body %}
    {% for post in post_list %}
        {% if post.draft %}
        {% else %}
        <h1><a href="{% url 'posts:detail' pk=post.pk %}" style="text-decoration:none;">{{ post.title }}</a></h1>
        <p>{{ post.author }} - {{ post.create_date}}</p>
        <p>Comments: {{ post.comments.count }}</p>
        <hr>
        {% endif %}
        {% empty %}
        <h1>No posts found...</h1>
    {% endfor %}
    <a href="{% url 'posts:create' %}" class="btn btn-success mt-4 px-5">Add a post</a>
{% endblock body %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Blog</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-primary mb-5">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'posts:all' %}">All Posts</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'posts:create' %}">Create Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'posts:post_draft_list' %}">View Drafts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:signup' %}">Signup</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
    {% block body %}
    {% endblock body %}
    </div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block body %}
    <h1>This is the home page</h1>
{% endblock body %}